version = 1

[[annotations]]
path = ["examples/simple/sources.yaml", "examples/aesop/sources.yaml"]
SPDX-FileCopyrightText = "2026 Alexandre Gomes Gaigalas <alganet@gmail.com>"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = "apysource/_defaults.py"
SPDX-FileCopyrightText = "2026 Alexandre Gomes Gaigalas <alganet@gmail.com>"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = "tests/fixtures/un_charter.html"
SPDX-FileCopyrightText = "United Nations"
SPDX-License-Identifier = "LicenseRef-PublicDomain"

[[annotations]]
path = "tests/fixtures/rfc2616.txt"
SPDX-FileCopyrightText = "1999 The Internet Society"
SPDX-License-Identifier = "LicenseRef-IETF"

[[annotations]]
path = "tests/fixtures/rfc8288.html"
SPDX-FileCopyrightText = "2017 IETF Trust and the persons identified as the document authors"
SPDX-License-Identifier = "LicenseRef-IETF"

[[annotations]]
path = "tests/fixtures/draft-thomson-hybi-http-timeout-03.html"
SPDX-FileCopyrightText = "2012 IETF Trust and the persons identified as the document authors"
SPDX-License-Identifier = "LicenseRef-IETF"

[[annotations]]
path = "tests/fixtures/markdown_syntax.md"
SPDX-FileCopyrightText = "2004 John Gruber"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "tests/fixtures/http.wiki"
SPDX-FileCopyrightText = "Wikipedia contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "tests/fixtures/mdn_origin.md"
SPDX-FileCopyrightText = "Mozilla Contributors"
SPDX-License-Identifier = "CC-BY-SA-2.5"
